version: "2"
services:
  web-panel:
    container_name: web-panel
    volumes:
      - npm-cache:/root/.npm
    working_dir: /app
    command: npm run serve
    restart: always
    build: .
    ports:
      - 8080:8080
      - 8081:8081
    links:
      - mongodb
  mongodb:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
volumes:
  npm-cache:
    external: false